#!/bin/bash
# Script para fazer deploy em Render

echo "🚀 Iniciando deployment em Render..."
echo ""
echo "Passos necessários:"
echo ""
echo "1️⃣  Abre: https://dashboard.render.com"
echo ""
echo "2️⃣  Clica 'New +' → 'Web Service'"
echo ""
echo "3️⃣  Conecta GitHub:"
echo "   - Clica 'Connect Repository'"
echo "   - Autoriza GitHub"
echo "   - Seleciona: joulfodayres/Trading212"
echo ""
echo "4️⃣  Configura Backend Service:"
echo ""
echo "   Name: trading212-bot-api"
echo "   Runtime: Python 3"
echo "   Build Command: pip install -r backend/requirements.txt"
echo "   Start Command: cd backend && uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo "   Region: Frankfurt (recomendado)"
echo "   Plan: Free"
echo ""
echo "5️⃣  Adiciona Environment Variables (Settings → Environment):"
echo ""
echo "   SUPABASE_URL=https://gocvyhizqggqaxryuplu.supabase.co"
echo "   SUPABASE_KEY=sb_publishable_283LZ_pvCLRaxYLaikfA7w_h4oSLVCW"
echo "   SUPABASE_JWT_SECRET=sb_secret_3qW7HsDKdwd69hmob1NHrQ_Tn--S4a4"
echo "   T212_API_KEY=40512867ZyijwBGwduNcUlkHinVZrCXhzxAqU"
echo "   T212_API_SECRET=iEQfVWUq3un1rGbM3ruzUWZweTRZYVLah-c8EFnCXW0"
echo "   T212_ENVIRONMENT=demo"
echo "   T212_BASE_URL=https://demo.trading212.com/api/v0"
echo "   FASTAPI_ENV=production"
echo "   FASTAPI_DEBUG=False"
echo "   JWT_SECRET_KEY=trading212-bot-secret-key-change-later"
echo "   JWT_ALGORITHM=HS256"
echo "   JWT_EXPIRATION_HOURS=24"
echo "   ENCRYPTION_KEY=mhRLQKMKc2d5fJ7pX8vN3qZ9wK1mL2nO3pR4sT5uV6w="
echo "   LOG_LEVEL=INFO"
echo ""
echo "6️⃣  Clica 'Deploy'"
echo ""
echo "7️⃣  Aguarda ~5-10 minutos"
echo ""
echo "✅ Backend URL: https://trading212-bot-api.onrender.com"
echo ""
